name: Matrix

on: 
  push:
  workflow_dispatch:
    
jobs:    
  build:
    runs-on: ubuntu-latest

    strategy:    
      matrix:
        cc: [gcc, clang]
        curl: [openssl, gnutls, nss]
        kerberos: [libkrb5, heimdal]

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.cc }} \
                                libcurl4-${{ matrix.curl }}-dev \
                                ${{ matrix.kerberos }}-dev
    - name: Display Configuration
      run: |
        echo "C Compiler:"
        ${CC} --version
        echo ""
        echo "Curl configuration:"
        curl-config --ssl-backends --version
        echo ""
        echo "Kerberos configuration:"
        krb5-config --all
      env:
        CC: ${{ matrix.cc }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: echo "./configure && make test"
