on:
  schedule:
  - cron: 01 13 * * 0
  workflow_dispatch:
name: Top 5
jobs:
  close-last-week:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: weekly-issue-closure
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: top5
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  createAnIssue:
    name: Create an issue
    runs-on: ubuntu-latest
    needs: [close-last-week]
    steps:
    - uses: actions/checkout@v2
    - name: Create an issue
      uses: bdougie/create-an-issue@e43b083ea71e22e77a81ffb4a55dacb2addb71ed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: .github/ISSUE_TEMPLATE/TOP5.md
